#pragma once

#include "Core/Core.h"

#define SPX_KEY_SCANCODE_MASK (1<<30)
#define SPX_SCANCODE_TO_KEYCODE(X)  (X | SPX_KEY_SCANCODE_MASK)

// Based on SDL keycodes
namespace Sphynx
{
	namespace
	{
		enum
		{
			SPX_SCANCODE_UNKNOWN = 0,

			/**
			 *  \name Usage page 0x07
			 *
			 *  These values are from usage page 0x07 (USB keyboard page).
			 */
			 /* @{ */

			SPX_SCANCODE_A = 4,
			SPX_SCANCODE_B = 5,
			SPX_SCANCODE_C = 6,
			SPX_SCANCODE_D = 7,
			SPX_SCANCODE_E = 8,
			SPX_SCANCODE_F = 9,
			SPX_SCANCODE_G = 10,
			SPX_SCANCODE_H = 11,
			SPX_SCANCODE_I = 12,
			SPX_SCANCODE_J = 13,
			SPX_SCANCODE_K = 14,
			SPX_SCANCODE_L = 15,
			SPX_SCANCODE_M = 16,
			SPX_SCANCODE_N = 17,
			SPX_SCANCODE_O = 18,
			SPX_SCANCODE_P = 19,
			SPX_SCANCODE_Q = 20,
			SPX_SCANCODE_R = 21,
			SPX_SCANCODE_S = 22,
			SPX_SCANCODE_T = 23,
			SPX_SCANCODE_U = 24,
			SPX_SCANCODE_V = 25,
			SPX_SCANCODE_W = 26,
			SPX_SCANCODE_X = 27,
			SPX_SCANCODE_Y = 28,
			SPX_SCANCODE_Z = 29,

			SPX_SCANCODE_1 = 30,
			SPX_SCANCODE_2 = 31,
			SPX_SCANCODE_3 = 32,
			SPX_SCANCODE_4 = 33,
			SPX_SCANCODE_5 = 34,
			SPX_SCANCODE_6 = 35,
			SPX_SCANCODE_7 = 36,
			SPX_SCANCODE_8 = 37,
			SPX_SCANCODE_9 = 38,
			SPX_SCANCODE_0 = 39,

			SPX_SCANCODE_RETURN = 40,
			SPX_SCANCODE_ESCAPE = 41,
			SPX_SCANCODE_BACKSPACE = 42,
			SPX_SCANCODE_TAB = 43,
			SPX_SCANCODE_SPACE = 44,

			SPX_SCANCODE_MINUS = 45,
			SPX_SCANCODE_EQUALS = 46,
			SPX_SCANCODE_LEFTBRACKET = 47,
			SPX_SCANCODE_RIGHTBRACKET = 48,
			SPX_SCANCODE_BACKSLASH = 49, /**< Located at the lower left of the return
										  *   key on ISO keyboards and at the right end
										  *   of the QWERTY row on ANSI keyboards.
										  *   Produces REVERSE SOLIDUS (backslash) and
										  *   VERTICAL LINE in a US layout, REVERSE
										  *   SOLIDUS and VERTICAL LINE in a UK Mac
										  *   layout, NUMBER SIGN and TILDE in a UK
										  *   Windows layout, DOLLAR SIGN and POUND SIGN
										  *   in a Swiss German layout, NUMBER SIGN and
										  *   APOSTROPHE in a German layout, GRAVE
										  *   ACCENT and POUND SIGN in a French Mac
										  *   layout, and ASTERISK and MICRO SIGN in a
										  *   French Windows layout.
										  */
			SPX_SCANCODE_NONUSHASH = 50, /**< ISO USB keyboards actually use this code
										  *   instead of 49 for the same key, but all
										  *   OSes I've seen treat the two codes
										  *   identically. So, as an implementor, unless
										  *   your keyboard generates both of those
										  *   codes and your OS treats them differently,
										  *   you should generate SPX_SCANCODE_BACKSLASH
										  *   instead of this code. As a user, you
										  *   should not rely on this code because SPX
										  *   will never generate it with most (all?)
										  *   keyboards.
										  */
			SPX_SCANCODE_SEMICOLON = 51,
			SPX_SCANCODE_APOSTROPHE = 52,
			SPX_SCANCODE_GRAVE = 53, /**< Located in the top left corner (on both ANSI
									  *   and ISO keyboards). Produces GRAVE ACCENT and
									  *   TILDE in a US Windows layout and in US and UK
									  *   Mac layouts on ANSI keyboards, GRAVE ACCENT
									  *   and NOT SIGN in a UK Windows layout, SECTION
									  *   SIGN and PLUS-MINUS SIGN in US and UK Mac
									  *   layouts on ISO keyboards, SECTION SIGN and
									  *   DEGREE SIGN in a Swiss German layout (Mac:
									  *   only on ISO keyboards), CIRCUMFLEX ACCENT and
									  *   DEGREE SIGN in a German layout (Mac: only on
									  *   ISO keyboards), SUPERSCRIPT TWO and TILDE in a
									  *   French Windows layout, COMMERCIAL AT and
									  *   NUMBER SIGN in a French Mac layout on ISO
									  *   keyboards, and LESS-THAN SIGN and GREATER-THAN
									  *   SIGN in a Swiss German, German, or French Mac
									  *   layout on ANSI keyboards.
									  */
			SPX_SCANCODE_COMMA = 54,
			SPX_SCANCODE_PERIOD = 55,
			SPX_SCANCODE_SLASH = 56,

			SPX_SCANCODE_CAPSLOCK = 57,

			SPX_SCANCODE_F1 = 58,
			SPX_SCANCODE_F2 = 59,
			SPX_SCANCODE_F3 = 60,
			SPX_SCANCODE_F4 = 61,
			SPX_SCANCODE_F5 = 62,
			SPX_SCANCODE_F6 = 63,
			SPX_SCANCODE_F7 = 64,
			SPX_SCANCODE_F8 = 65,
			SPX_SCANCODE_F9 = 66,
			SPX_SCANCODE_F10 = 67,
			SPX_SCANCODE_F11 = 68,
			SPX_SCANCODE_F12 = 69,

			SPX_SCANCODE_PRINTSCREEN = 70,
			SPX_SCANCODE_SCROLLLOCK = 71,
			SPX_SCANCODE_PAUSE = 72,
			SPX_SCANCODE_INSERT = 73, /**< insert on PC, help on some Mac keyboards (but
										   does send code 73, not 117) */
			SPX_SCANCODE_HOME = 74,
			SPX_SCANCODE_PAGEUP = 75,
			SPX_SCANCODE_DELETE = 76,
			SPX_SCANCODE_END = 77,
			SPX_SCANCODE_PAGEDOWN = 78,
			SPX_SCANCODE_RIGHT = 79,
			SPX_SCANCODE_LEFT = 80,
			SPX_SCANCODE_DOWN = 81,
			SPX_SCANCODE_UP = 82,

			SPX_SCANCODE_NUMLOCKCLEAR = 83, /**< num lock on PC, clear on Mac keyboards
											 */
			SPX_SCANCODE_KP_DIVIDE = 84,
			SPX_SCANCODE_KP_MULTIPLY = 85,
			SPX_SCANCODE_KP_MINUS = 86,
			SPX_SCANCODE_KP_PLUS = 87,
			SPX_SCANCODE_KP_ENTER = 88,
			SPX_SCANCODE_KP_1 = 89,
			SPX_SCANCODE_KP_2 = 90,
			SPX_SCANCODE_KP_3 = 91,
			SPX_SCANCODE_KP_4 = 92,
			SPX_SCANCODE_KP_5 = 93,
			SPX_SCANCODE_KP_6 = 94,
			SPX_SCANCODE_KP_7 = 95,
			SPX_SCANCODE_KP_8 = 96,
			SPX_SCANCODE_KP_9 = 97,
			SPX_SCANCODE_KP_0 = 98,
			SPX_SCANCODE_KP_PERIOD = 99,

			SPX_SCANCODE_NONUSBACKSLASH = 100, /**< This is the additional key that ISO
												*   keyboards have over ANSI ones,
												*   located between left shift and Y.
												*   Produces GRAVE ACCENT and TILDE in a
												*   US or UK Mac layout, REVERSE SOLIDUS
												*   (backslash) and VERTICAL LINE in a
												*   US or UK Windows layout, and
												*   LESS-THAN SIGN and GREATER-THAN SIGN
												*   in a Swiss German, German, or French
												*   layout. */
			SPX_SCANCODE_APPLICATION = 101, /**< windows contextual menu, compose */
			SPX_SCANCODE_POWER = 102, /**< The USB document says this is a status flag,
									   *   not a physical key - but some Mac keyboards
									   *   do have a power key. */
			SPX_SCANCODE_KP_EQUALS = 103,
			SPX_SCANCODE_F13 = 104,
			SPX_SCANCODE_F14 = 105,
			SPX_SCANCODE_F15 = 106,
			SPX_SCANCODE_F16 = 107,
			SPX_SCANCODE_F17 = 108,
			SPX_SCANCODE_F18 = 109,
			SPX_SCANCODE_F19 = 110,
			SPX_SCANCODE_F20 = 111,
			SPX_SCANCODE_F21 = 112,
			SPX_SCANCODE_F22 = 113,
			SPX_SCANCODE_F23 = 114,
			SPX_SCANCODE_F24 = 115,
			SPX_SCANCODE_EXECUTE = 116,
			SPX_SCANCODE_HELP = 117,    /**< AL Integrated Help Center */
			SPX_SCANCODE_MENU = 118,    /**< Menu (show menu) */
			SPX_SCANCODE_SELECT = 119,
			SPX_SCANCODE_STOP = 120,    /**< AC Stop */
			SPX_SCANCODE_AGAIN = 121,   /**< AC Redo/Repeat */
			SPX_SCANCODE_UNDO = 122,    /**< AC Undo */
			SPX_SCANCODE_CUT = 123,     /**< AC Cut */
			SPX_SCANCODE_COPY = 124,    /**< AC Copy */
			SPX_SCANCODE_PASTE = 125,   /**< AC Paste */
			SPX_SCANCODE_FIND = 126,    /**< AC Find */
			SPX_SCANCODE_MUTE = 127,
			SPX_SCANCODE_VOLUMEUP = 128,
			SPX_SCANCODE_VOLUMEDOWN = 129,
			/* not sure whether there's a reason to enable these */
			/*     SPX_SCANCODE_LOCKINGCAPSLOCK = 130,  */
			/*     SPX_SCANCODE_LOCKINGNUMLOCK = 131, */
			/*     SPX_SCANCODE_LOCKINGSCROLLLOCK = 132, */
			SPX_SCANCODE_KP_COMMA = 133,
			SPX_SCANCODE_KP_EQUALSAS400 = 134,

			SPX_SCANCODE_INTERNATIONAL1 = 135, /**< used on Asian keyboards, see
													footnotes in USB doc */
			SPX_SCANCODE_INTERNATIONAL2 = 136,
			SPX_SCANCODE_INTERNATIONAL3 = 137, /**< Yen */
			SPX_SCANCODE_INTERNATIONAL4 = 138,
			SPX_SCANCODE_INTERNATIONAL5 = 139,
			SPX_SCANCODE_INTERNATIONAL6 = 140,
			SPX_SCANCODE_INTERNATIONAL7 = 141,
			SPX_SCANCODE_INTERNATIONAL8 = 142,
			SPX_SCANCODE_INTERNATIONAL9 = 143,
			SPX_SCANCODE_LANG1 = 144, /**< Hangul/English toggle */
			SPX_SCANCODE_LANG2 = 145, /**< Hanja conversion */
			SPX_SCANCODE_LANG3 = 146, /**< Katakana */
			SPX_SCANCODE_LANG4 = 147, /**< Hiragana */
			SPX_SCANCODE_LANG5 = 148, /**< Zenkaku/Hankaku */
			SPX_SCANCODE_LANG6 = 149, /**< reserved */
			SPX_SCANCODE_LANG7 = 150, /**< reserved */
			SPX_SCANCODE_LANG8 = 151, /**< reserved */
			SPX_SCANCODE_LANG9 = 152, /**< reserved */

			SPX_SCANCODE_ALTERASE = 153,    /**< Erase-Eaze */
			SPX_SCANCODE_SYSREQ = 154,
			SPX_SCANCODE_CANCEL = 155,      /**< AC Cancel */
			SPX_SCANCODE_CLEAR = 156,
			SPX_SCANCODE_PRIOR = 157,
			SPX_SCANCODE_RETURN2 = 158,
			SPX_SCANCODE_SEPARATOR = 159,
			SPX_SCANCODE_OUT = 160,
			SPX_SCANCODE_OPER = 161,
			SPX_SCANCODE_CLEARAGAIN = 162,
			SPX_SCANCODE_CRSEL = 163,
			SPX_SCANCODE_EXSEL = 164,

			SPX_SCANCODE_KP_00 = 176,
			SPX_SCANCODE_KP_000 = 177,
			SPX_SCANCODE_THOUSANDSSEPARATOR = 178,
			SPX_SCANCODE_DECIMALSEPARATOR = 179,
			SPX_SCANCODE_CURRENCYUNIT = 180,
			SPX_SCANCODE_CURRENCYSUBUNIT = 181,
			SPX_SCANCODE_KP_LEFTPAREN = 182,
			SPX_SCANCODE_KP_RIGHTPAREN = 183,
			SPX_SCANCODE_KP_LEFTBRACE = 184,
			SPX_SCANCODE_KP_RIGHTBRACE = 185,
			SPX_SCANCODE_KP_TAB = 186,
			SPX_SCANCODE_KP_BACKSPACE = 187,
			SPX_SCANCODE_KP_A = 188,
			SPX_SCANCODE_KP_B = 189,
			SPX_SCANCODE_KP_C = 190,
			SPX_SCANCODE_KP_D = 191,
			SPX_SCANCODE_KP_E = 192,
			SPX_SCANCODE_KP_F = 193,
			SPX_SCANCODE_KP_XOR = 194,
			SPX_SCANCODE_KP_POWER = 195,
			SPX_SCANCODE_KP_PERCENT = 196,
			SPX_SCANCODE_KP_LESS = 197,
			SPX_SCANCODE_KP_GREATER = 198,
			SPX_SCANCODE_KP_AMPERSAND = 199,
			SPX_SCANCODE_KP_DBLAMPERSAND = 200,
			SPX_SCANCODE_KP_VERTICALBAR = 201,
			SPX_SCANCODE_KP_DBLVERTICALBAR = 202,
			SPX_SCANCODE_KP_COLON = 203,
			SPX_SCANCODE_KP_HASH = 204,
			SPX_SCANCODE_KP_SPACE = 205,
			SPX_SCANCODE_KP_AT = 206,
			SPX_SCANCODE_KP_EXCLAM = 207,
			SPX_SCANCODE_KP_MEMSTORE = 208,
			SPX_SCANCODE_KP_MEMRECALL = 209,
			SPX_SCANCODE_KP_MEMCLEAR = 210,
			SPX_SCANCODE_KP_MEMADD = 211,
			SPX_SCANCODE_KP_MEMSUBTRACT = 212,
			SPX_SCANCODE_KP_MEMMULTIPLY = 213,
			SPX_SCANCODE_KP_MEMDIVIDE = 214,
			SPX_SCANCODE_KP_PLUSMINUS = 215,
			SPX_SCANCODE_KP_CLEAR = 216,
			SPX_SCANCODE_KP_CLEARENTRY = 217,
			SPX_SCANCODE_KP_BINARY = 218,
			SPX_SCANCODE_KP_OCTAL = 219,
			SPX_SCANCODE_KP_DECIMAL = 220,
			SPX_SCANCODE_KP_HEXADECIMAL = 221,

			SPX_SCANCODE_LCTRL = 224,
			SPX_SCANCODE_LSHIFT = 225,
			SPX_SCANCODE_LALT = 226, /**< alt, option */
			SPX_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
			SPX_SCANCODE_RCTRL = 228,
			SPX_SCANCODE_RSHIFT = 229,
			SPX_SCANCODE_RALT = 230, /**< alt gr, option */
			SPX_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

			SPX_SCANCODE_MODE = 257,    /**< I'm not sure if this is really not covered
										 *   by any of the above, but since there's a
										 *   special SPX_KMOD_MODE for it I'm adding it here
										 */

										 /* @} *//* Usage page 0x07 */

										 /**
										  *  \name Usage page 0x0C
										  *
										  *  These values are mapped from usage page 0x0C (USB consumer page).
										  *  See https://usb.org/sites/default/files/hut1_2.pdf
										  *
										  *  There are way more keys in the spec than we can represent in the
										  *  current scancode range, so pick the ones that commonly come up in
										  *  real world usage.
										  */
										  /* @{ */

			SPX_SCANCODE_AUDIONEXT = 258,
			SPX_SCANCODE_AUDIOPREV = 259,
			SPX_SCANCODE_AUDIOSTOP = 260,
			SPX_SCANCODE_AUDIOPLAY = 261,
			SPX_SCANCODE_AUDIOMUTE = 262,
			SPX_SCANCODE_MEDIASELECT = 263,
			SPX_SCANCODE_WWW = 264,             /**< AL Internet Browser */
			SPX_SCANCODE_MAIL = 265,
			SPX_SCANCODE_CALCULATOR = 266,      /**< AL Calculator */
			SPX_SCANCODE_COMPUTER = 267,
			SPX_SCANCODE_AC_SEARCH = 268,       /**< AC Search */
			SPX_SCANCODE_AC_HOME = 269,         /**< AC Home */
			SPX_SCANCODE_AC_BACK = 270,         /**< AC Back */
			SPX_SCANCODE_AC_FORWARD = 271,      /**< AC Forward */
			SPX_SCANCODE_AC_STOP = 272,         /**< AC Stop */
			SPX_SCANCODE_AC_REFRESH = 273,      /**< AC Refresh */
			SPX_SCANCODE_AC_BOOKMARKS = 274,    /**< AC Bookmarks */

			/* @} *//* Usage page 0x0C */

			/**
			 *  \name Walther keys
			 *
			 *  These are values that Christian Walther added (for mac keyboard?).
			 */
			 /* @{ */

			SPX_SCANCODE_BRIGHTNESSDOWN = 275,
			SPX_SCANCODE_BRIGHTNESSUP = 276,
			SPX_SCANCODE_DISPLAYSWITCH = 277, /**< display mirroring/dual display
												   switch, video mode switch */
			SPX_SCANCODE_KBDILLUMTOGGLE = 278,
			SPX_SCANCODE_KBDILLUMDOWN = 279,
			SPX_SCANCODE_KBDILLUMUP = 280,
			SPX_SCANCODE_EJECT = 281,
			SPX_SCANCODE_SLEEP = 282,           /**< SC System Sleep */

			SPX_SCANCODE_APP1 = 283,
			SPX_SCANCODE_APP2 = 284,

			/* @} *//* Walther keys */

			/**
			 *  \name Usage page 0x0C (additional media keys)
			 *
			 *  These values are mapped from usage page 0x0C (USB consumer page).
			 */
			 /* @{ */

			SPX_SCANCODE_AUDIOREWIND = 285,
			SPX_SCANCODE_AUDIOFASTFORWARD = 286,

			/* @} *//* Usage page 0x0C (additional media keys) */

			/**
			 *  \name Mobile keys
			 *
			 *  These are values that are often used on mobile phones.
			 */
			 /* @{ */

			SPX_SCANCODE_SOFTLEFT = 287, /**< Usually situated below the display on phones and
											  used as a multi-function feature key for selecting
											  a software defined function shown on the bottom left
											  of the display. */
			SPX_SCANCODE_SOFTRIGHT = 288, /**< Usually situated below the display on phones and
											   used as a multi-function feature key for selecting
											   a software defined function shown on the bottom right
											   of the display. */
			SPX_SCANCODE_CALL = 289, /**< Used for accepting phone calls. */
			SPX_SCANCODE_ENDCALL = 290, /**< Used for rejecting phone calls. */

			/* @} *//* Mobile keys */

			/* Add any other keys here. */

			SPX_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes
										 for array bounds */
		};
	}

	enum SPHYNX_API Keycode
	{
		SPX_KEY_UNKNOWN = 0,

		SPX_KEY_RETURN = '\r',
		SPX_KEY_ESCAPE = '\x1B',
		SPX_KEY_BACKSPACE = '\b',
		SPX_KEY_TAB = '\t',
		SPX_KEY_SPACE = ' ',
		SPX_KEY_EXCLAIM = '!',
		SPX_KEY_QUOTEDBL = '"',
		SPX_KEY_HASH = '#',
		SPX_KEY_PERCENT = '%',
		SPX_KEY_DOLLAR = '$',
		SPX_KEY_AMPERSAND = '&',
		SPX_KEY_QUOTE = '\'',
		SPX_KEY_LEFTPAREN = '(',
		SPX_KEY_RIGHTPAREN = ')',
		SPX_KEY_ASTERISK = '*',
		SPX_KEY_PLUS = '+',
		SPX_KEY_COMMA = ',',
		SPX_KEY_MINUS = '-',
		SPX_KEY_PERIOD = '.',
		SPX_KEY_SLASH = '/',
		SPX_KEY_0 = '0',
		SPX_KEY_1 = '1',
		SPX_KEY_2 = '2',
		SPX_KEY_3 = '3',
		SPX_KEY_4 = '4',
		SPX_KEY_5 = '5',
		SPX_KEY_6 = '6',
		SPX_KEY_7 = '7',
		SPX_KEY_8 = '8',
		SPX_KEY_9 = '9',
		SPX_KEY_COLON = ':',
		SPX_KEY_SEMICOLON = ';',
		SPX_KEY_LESS = '<',
		SPX_KEY_EQUALS = '=',
		SPX_KEY_GREATER = '>',
		SPX_KEY_QUESTION = '?',
		SPX_KEY_AT = '@',

		/*
		   Skip uppercase letters
		 */

		SPX_KEY_LEFTBRACKET = '[',
		SPX_KEY_BACKSLASH = '\\',
		SPX_KEY_RIGHTBRACKET = ']',
		SPX_KEY_CARET = '^',
		SPX_KEY_UNDERSCORE = '_',
		SPX_KEY_BACKQUOTE = '`',
		SPX_KEY_A = 'a',
		SPX_KEY_B = 'b',
		SPX_KEY_C = 'c',
		SPX_KEY_D = 'd',
		SPX_KEY_E = 'e',
		SPX_KEY_F = 'f',
		SPX_KEY_G = 'g',
		SPX_KEY_H = 'h',
		SPX_KEY_I = 'i',
		SPX_KEY_J = 'j',
		SPX_KEY_K = 'k',
		SPX_KEY_L = 'l',
		SPX_KEY_M = 'm',
		SPX_KEY_N = 'n',
		SPX_KEY_O = 'o',
		SPX_KEY_P = 'p',
		SPX_KEY_Q = 'q',
		SPX_KEY_R = 'r',
		SPX_KEY_S = 's',
		SPX_KEY_T = 't',
		SPX_KEY_U = 'u',
		SPX_KEY_V = 'v',
		SPX_KEY_W = 'w',
		SPX_KEY_X = 'x',
		SPX_KEY_Y = 'y',
		SPX_KEY_Z = 'z',

		SPX_KEY_CAPSLOCK = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CAPSLOCK),

		SPX_KEY_F1 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F1),
		SPX_KEY_F2 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F2),
		SPX_KEY_F3 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F3),
		SPX_KEY_F4 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F4),
		SPX_KEY_F5 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F5),
		SPX_KEY_F6 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F6),
		SPX_KEY_F7 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F7),
		SPX_KEY_F8 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F8),
		SPX_KEY_F9 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F9),
		SPX_KEY_F10 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F10),
		SPX_KEY_F11 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F11),
		SPX_KEY_F12 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F12),

		SPX_KEY_PRINTSCREEN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_PRINTSCREEN),
		SPX_KEY_SCROLLLOCK = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_SCROLLLOCK),
		SPX_KEY_PAUSE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_PAUSE),
		SPX_KEY_INSERT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_INSERT),
		SPX_KEY_HOME = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_HOME),
		SPX_KEY_PAGEUP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_PAGEUP),
		SPX_KEY_DELETE = '\x7F',
		SPX_KEY_END = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_END),
		SPX_KEY_PAGEDOWN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_PAGEDOWN),
		SPX_KEY_RIGHT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_RIGHT),
		SPX_KEY_LEFT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_LEFT),
		SPX_KEY_DOWN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_DOWN),
		SPX_KEY_UP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_UP),

		SPX_KEY_NUMLOCKCLEAR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_NUMLOCKCLEAR),
		SPX_KEY_KP_DIVIDE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_DIVIDE),
		SPX_KEY_KP_MULTIPLY = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MULTIPLY),
		SPX_KEY_KP_MINUS = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MINUS),
		SPX_KEY_KP_PLUS = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_PLUS),
		SPX_KEY_KP_ENTER = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_ENTER),
		SPX_KEY_KP_1 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_1),
		SPX_KEY_KP_2 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_2),
		SPX_KEY_KP_3 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_3),
		SPX_KEY_KP_4 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_4),
		SPX_KEY_KP_5 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_5),
		SPX_KEY_KP_6 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_6),
		SPX_KEY_KP_7 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_7),
		SPX_KEY_KP_8 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_8),
		SPX_KEY_KP_9 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_9),
		SPX_KEY_KP_0 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_0),
		SPX_KEY_KP_PERIOD = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_PERIOD),

		SPX_KEY_APPLICATION = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_APPLICATION),
		SPX_KEY_POWER = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_POWER),
		SPX_KEY_KP_EQUALS = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_EQUALS),
		SPX_KEY_F13 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F13),
		SPX_KEY_F14 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F14),
		SPX_KEY_F15 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F15),
		SPX_KEY_F16 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F16),
		SPX_KEY_F17 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F17),
		SPX_KEY_F18 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F18),
		SPX_KEY_F19 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F19),
		SPX_KEY_F20 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F20),
		SPX_KEY_F21 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F21),
		SPX_KEY_F22 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F22),
		SPX_KEY_F23 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F23),
		SPX_KEY_F24 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_F24),
		SPX_KEY_EXECUTE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_EXECUTE),
		SPX_KEY_HELP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_HELP),
		SPX_KEY_MENU = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_MENU),
		SPX_KEY_SELECT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_SELECT),
		SPX_KEY_STOP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_STOP),
		SPX_KEY_AGAIN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AGAIN),
		SPX_KEY_UNDO = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_UNDO),
		SPX_KEY_CUT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CUT),
		SPX_KEY_COPY = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_COPY),
		SPX_KEY_PASTE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_PASTE),
		SPX_KEY_FIND = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_FIND),
		SPX_KEY_MUTE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_MUTE),
		SPX_KEY_VOLUMEUP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_VOLUMEUP),
		SPX_KEY_VOLUMEDOWN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_VOLUMEDOWN),
		SPX_KEY_KP_COMMA = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_COMMA),
		SPX_KEY_KP_EQUALSAS400 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_EQUALSAS400),

		SPX_KEY_ALTERASE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_ALTERASE),
		SPX_KEY_SYSREQ = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_SYSREQ),
		SPX_KEY_CANCEL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CANCEL),
		SPX_KEY_CLEAR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CLEAR),
		SPX_KEY_PRIOR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_PRIOR),
		SPX_KEY_RETURN2 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_RETURN2),
		SPX_KEY_SEPARATOR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_SEPARATOR),
		SPX_KEY_OUT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_OUT),
		SPX_KEY_OPER = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_OPER),
		SPX_KEY_CLEARAGAIN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CLEARAGAIN),
		SPX_KEY_CRSEL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CRSEL),
		SPX_KEY_EXSEL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_EXSEL),

		SPX_KEY_KP_00 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_00),
		SPX_KEY_KP_000 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_000),
		SPX_KEY_THOUSANDSSEPARATOR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_THOUSANDSSEPARATOR),
		SPX_KEY_DECIMALSEPARATOR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_DECIMALSEPARATOR),
		SPX_KEY_CURRENCYUNIT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CURRENCYUNIT),
		SPX_KEY_CURRENCYSUBUNIT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CURRENCYSUBUNIT),
		SPX_KEY_KP_LEFTPAREN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_LEFTPAREN),
		SPX_KEY_KP_RIGHTPAREN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_RIGHTPAREN),
		SPX_KEY_KP_LEFTBRACE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_LEFTBRACE),
		SPX_KEY_KP_RIGHTBRACE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_RIGHTBRACE),
		SPX_KEY_KP_TAB = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_TAB),
		SPX_KEY_KP_BACKSPACE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_BACKSPACE),
		SPX_KEY_KP_A = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_A),
		SPX_KEY_KP_B = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_B),
		SPX_KEY_KP_C = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_C),
		SPX_KEY_KP_D = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_D),
		SPX_KEY_KP_E = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_E),
		SPX_KEY_KP_F = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_F),
		SPX_KEY_KP_XOR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_XOR),
		SPX_KEY_KP_POWER = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_POWER),
		SPX_KEY_KP_PERCENT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_PERCENT),
		SPX_KEY_KP_LESS = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_LESS),
		SPX_KEY_KP_GREATER = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_GREATER),
		SPX_KEY_KP_AMPERSAND = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_AMPERSAND),
		SPX_KEY_KP_DBLAMPERSAND = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_DBLAMPERSAND),
		SPX_KEY_KP_VERTICALBAR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_VERTICALBAR),
		SPX_KEY_KP_DBLVERTICALBAR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_DBLVERTICALBAR),
		SPX_KEY_KP_COLON = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_COLON),
		SPX_KEY_KP_HASH = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_HASH),
		SPX_KEY_KP_SPACE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_SPACE),
		SPX_KEY_KP_AT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_AT),
		SPX_KEY_KP_EXCLAM = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_EXCLAM),
		SPX_KEY_KP_MEMSTORE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MEMSTORE),
		SPX_KEY_KP_MEMRECALL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MEMRECALL),
		SPX_KEY_KP_MEMCLEAR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MEMCLEAR),
		SPX_KEY_KP_MEMADD = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MEMADD),
		SPX_KEY_KP_MEMSUBTRACT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MEMSUBTRACT),
		SPX_KEY_KP_MEMMULTIPLY = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MEMMULTIPLY),
		SPX_KEY_KP_MEMDIVIDE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_MEMDIVIDE),
		SPX_KEY_KP_PLUSMINUS = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_PLUSMINUS),
		SPX_KEY_KP_CLEAR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_CLEAR),
		SPX_KEY_KP_CLEARENTRY = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_CLEARENTRY),
		SPX_KEY_KP_BINARY = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_BINARY),
		SPX_KEY_KP_OCTAL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_OCTAL),
		SPX_KEY_KP_DECIMAL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_DECIMAL),
		SPX_KEY_KP_HEXADECIMAL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KP_HEXADECIMAL),

		SPX_KEY_LCTRL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_LCTRL),
		SPX_KEY_LSHIFT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_LSHIFT),
		SPX_KEY_LALT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_LALT),
		SPX_KEY_LGUI = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_LGUI),
		SPX_KEY_RCTRL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_RCTRL),
		SPX_KEY_RSHIFT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_RSHIFT),
		SPX_KEY_RALT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_RALT),
		SPX_KEY_RGUI = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_RGUI),

		SPX_KEY_MODE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_MODE),

		SPX_KEY_AUDIONEXT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AUDIONEXT),
		SPX_KEY_AUDIOPREV = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AUDIOPREV),
		SPX_KEY_AUDIOSTOP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AUDIOSTOP),
		SPX_KEY_AUDIOPLAY = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AUDIOPLAY),
		SPX_KEY_AUDIOMUTE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AUDIOMUTE),
		SPX_KEY_MEDIASELECT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_MEDIASELECT),
		SPX_KEY_WWW = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_WWW),
		SPX_KEY_MAIL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_MAIL),
		SPX_KEY_CALCULATOR = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CALCULATOR),
		SPX_KEY_COMPUTER = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_COMPUTER),
		SPX_KEY_AC_SEARCH = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AC_SEARCH),
		SPX_KEY_AC_HOME = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AC_HOME),
		SPX_KEY_AC_BACK = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AC_BACK),
		SPX_KEY_AC_FORWARD = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AC_FORWARD),
		SPX_KEY_AC_STOP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AC_STOP),
		SPX_KEY_AC_REFRESH = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AC_REFRESH),
		SPX_KEY_AC_BOOKMARKS = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AC_BOOKMARKS),

		SPX_KEY_BRIGHTNESSDOWN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_BRIGHTNESSDOWN),
		SPX_KEY_BRIGHTNESSUP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_BRIGHTNESSUP),
		SPX_KEY_DISPLAYSWITCH = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_DISPLAYSWITCH),
		SPX_KEY_KBDILLUMTOGGLE = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KBDILLUMTOGGLE),
		SPX_KEY_KBDILLUMDOWN = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KBDILLUMDOWN),
		SPX_KEY_KBDILLUMUP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_KBDILLUMUP),
		SPX_KEY_EJECT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_EJECT),
		SPX_KEY_SLEEP = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_SLEEP),
		SPX_KEY_APP1 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_APP1),
		SPX_KEY_APP2 = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_APP2),

		SPX_KEY_AUDIOREWIND = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AUDIOREWIND),
		SPX_KEY_AUDIOFASTFORWARD = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_AUDIOFASTFORWARD),

		SPX_KEY_SOFTLEFT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_SOFTLEFT),
		SPX_KEY_SOFTRIGHT = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_SOFTRIGHT),
		SPX_KEY_CALL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_CALL),
		SPX_KEY_ENDCALL = SPX_SCANCODE_TO_KEYCODE(SPX_SCANCODE_ENDCALL)
	};
}

#undef SPX_SCANCODE_TO_KEYCODE
#undef SPX_KEY_SCANCODE_MASK
